### ISSUE TITLE
Commented lines not highlighted correctly

### ISSUE THREAD

**Issue by OliverJAsh** [Sidneys1/GitConfigVSCode#3]
I would expect all commented lines to appear faded, however they don't:

![image](https://user-images.githubusercontent.com/921609/37707495-36d90664-2cfb-11e8-892c-b44b95986874.png)

**Comment by Sidneys1** [comment]
Fixed in v1.0.1 (b9f96a598697a51682881009d8a135e8c862a9e7)

**Comment by OliverJAsh** [comment]
Thank you!
