### ISSUE TITLE
Alternate .gitconfig location is not handled

### ISSUE THREAD

**Issue by anthonygelibert** [Sidneys1/GitConfigVSCode#4]
Hi,

`$HOME/.gitconfig` is not the only one location for the `git` settings file.
`$XDG_CONFIG_HOME/git/config`is another.

Is it possible to correct the file association? 

Regards,
Anthony.

**Comment by Sidneys1** [comment]
The way VSCode selects an extension to associate a particular file is via file extension. I've added `config` as a supported file extension, but the built-in support for `Config` files is overriding my extension. 

To make my `gitconfig` plugin the default for `config` files, add this to your `settings.json`:

```json
"files.associations": {
    "config": "gitconfig"
}
```

**Comment by anthonygelibert** [comment]
Thank you!
