### ISSUE TITLE
Matching on "config" extension is far too broad

### ISSUE THREAD

**Issue by ralish** [Sidneys1/GitConfigVSCode#6]
The extension manifest includes `config` as an associated extension. This is far too broad and results in any file ending with `config` being classified as a _Git Config_ syntax file (e.g. `app-config`). I'm open to ideas on the best way to fix this but my inclination would be to remove this extension altogether. The other listed extensions should cover all standard scenarios, and for edge cases, the user can either manually set the language syntax to _Git Config_ or set a file association mapping via their user or workspace preferences.

**Comment by Sidneys1** [comment]
I had a feeling this would be the case. However, the built-in "config" plugin should take precedence over mine... I will consider removing.

Get Outlook for Android

________________________________

**Comment by ralish** [comment]
Thanks! And yeah, apparently not. Maybe something changed in a recent release, but in my case I've got several files which are actually Python being set as _Git Config_ files. They all end in `-config`, though the dash itself appears to be irrelevant.
